# Generated by Django 2.2.2 on 2019-07-07 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembrosTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='perfis.Membro')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_prazo', models.DateTimeField()),
                ('hora_prazo', models.TimeField()),
                ('statusProjeto', models.CharField(choices=[('PENDENTE', 'pendente'), ('EM DESENVOLVIMENTO', 'em desenvolvimento'), ('FEITO', 'finalizado')], max_length=1)),
                ('dono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='perfis.Gestor')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dono', to='perfis.Gestor')),
                ('membros', models.ManyToManyField(related_name='membros_time', through='projetos.MembrosTime', to='perfis.Membro')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=255)),
                ('data_prazo', models.DateTimeField()),
                ('hora_prazo', models.TimeField()),
                ('statusTarefa', models.CharField(choices=[('PENDENTE', 'pendente'), ('EM DESENVOLVIMENTO', 'em desenvolvimento'), ('FEITO', 'finalizado')], max_length=1)),
                ('p', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos.Projeto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='perfis.Membro')),
            ],
        ),
        migrations.AddField(
            model_name='membrostime',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time', to='projetos.Time'),
        ),
    ]
