# Generated by Django 2.2.2 on 2019-07-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='hr_prazo',
            new_name='hora_prazo',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='hr_prazo',
            new_name='hora_prazo',
        ),
    ]
