# Generated by Django 2.2.2 on 2019-07-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='statusProjeto',
            field=models.CharField(choices=[('PENDENTE', 'pendente'), ('EM DESENVOLVIMENTO', 'em desenvolvimento'), ('FEITO', 'finalizado')], max_length=20),
        ),
    ]
