# Generated by Django 2.2.2 on 2019-07-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20190707_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='statusTarefa',
            field=models.CharField(choices=[('PENDENTE', 'pendente'), ('EM DESENVOLVIMENTO', 'em desenvolvimento'), ('FEITO', 'finalizado')], max_length=20),
        ),
    ]
