# Generated by Django 2.2.2 on 2019-07-07 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20190707_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='tarefas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos.Tarefa'),
        ),
    ]
