# Generated by Django 2.2.2 on 2019-07-08 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_auto_20190708_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsavel', to='perfis.Membro'),
        ),
    ]
