# Generated by Django 2.2.2 on 2019-07-07 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_auto_20190707_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='tarefas',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='p',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projetos.Projeto'),
        ),
    ]
