# Generated by Django 2.2.2 on 2019-07-07 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_remove_gestor_projetos'),
        ('projetos', '0004_auto_20190707_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='perfis.Gestor'),
        ),
    ]
