# Generated by Django 2.2.2 on 2019-07-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_auto_20190708_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='p',
            new_name='projeto',
        ),
    ]
