# Generated by Django 2.2.2 on 2019-07-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_auto_20190706_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
