# Generated by Django 2.2.2 on 2019-07-06 21:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_auto_20190706_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gestor',
            name='projetos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='projetos.Projeto'),
        ),
    ]
