# Generated by Django 2.2.2 on 2019-07-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20190706_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='projetos',
        ),
    ]
